export_full_mix: true
export_individual_tracks: true
export_part_panned_tracks: true
export_part_predominant_tracks: true
export_part_missing_tracks: true

cancel_exports_after_failure: true

panned_part_volume: 2
panned_part_position: -1
predominant_part_volume: 3
full_mix_width: 0.6
